### ISSUE TITLE
doesnt quit when pressing on it and how do i change the mapping?

### ISSUE THREAD

**Issue by imstupidwithlinux** [FlorianKempenich/Deckpad#2]
title is basicly all i want to know mainly the "press to quit" problem when i tap in the square it opens the on screen keyboard but nothing else happens, and i have the normal gamepad layout for the steam deck selected and it still has a weird layout once connected to the pc

**Comment by FlorianKempenich** [comment]
Hey,
This is a duplicate of https://github.com/FlorianKempenich/Deckpad/issues/1. 
I'll close this one and answer on the other one
