### ISSUE TITLE
Script keeps failing to launch virtual here

### ISSUE THREAD

**Issue by PureRussianVodka** [FlorianKempenich/Deckpad#3]
The script is failing to launch virtual here, and the touch is not working. I might be doing something wrong, and it would be nice to see an installation video rather than some instructions, for people like me who don't know Linux or are good with computers.

**Comment by FlorianKempenich** [comment]
Failing to launch `virtualhere` ? What's the error message?
Did you follow steps 4 and 5 of the setup instructions?

> 4. Download: [VirtualHere USB Server for Linux (x86_64)](https://www.virtualhere.com/sites/default/files/usbserver/vhusbdx86_64)
> 5. Put in ~/Deckpad/virtualhere/

An install video is a nice suggestion, but I have no time to work on that at the moment.
