### ISSUE TITLE
Deckpad fails to open VirtualHere

### ISSUE THREAD

**Issue by cheesebob04** [FlorianKempenich/Deckpad#4]
Opening through the Steam shortcut returns "Failed to launch 'PC Controller'". Yes, I did update it to include --fullscreen. After that, I tried digging around in the files to manually run the stuff so I could actually get any error message (though I've barely used Linux, I don't know what I'm doing). I've run all of the .sh files, though they don't say or prompt any success or failure message, so I'm not sure if it did anything.

In the image, I manually ran what I thought to be was the function to startup VirtualHere (function start_virtualhere), returning Exit 127 and the virtualhere_pid (which changed from 9237 to 9257 because I deleted the file and reran vhusbd). 
![IMG_3597](https://user-images.githubusercontent.com/75389012/218227630-6064184d-2f77-4ffe-8a31-7d731c52cb01.jpg)

**Comment by FlorianKempenich** [comment]
Hi,

Although I appreciate you tried to debug the issue on your own, I would not recommend running commands you don't understand. Running code you don't understand can potentially change settings you wouldn't know how to restore, corrupt your machine, or even plain hacking it making it vulnerable.

My code isn't harmful, but it can leave the system in a corrupted state, if that happens, just run these 2 commands to fix it (they're from the warnings at the top of the README)
```
sudo chmod 666 /sys/class/backlight/amdgpu_bl0/brightness
sudo systemctl unmask sleep.target suspend.target hibernate.target hybrid-sleep.target >/dev/null 2>&1
```

Don't worry about these `pid` files, you can just remove them if they're leftover. They're used to kill the processes started by Deckpad, but any process you ran will be killed upon restart anyway, so just restart once, and remove these pid files and you're all good (also do the 2 commands in case your deck doesn't go to sleep anymore)

Now, for your issue, could you show me the properties of the "PC Controller" steam 'game'. I want to make sure they look like this: https://github.com/FlorianKempenich/Deckpad#on-steam-deck

Also, did you do `chmod +x vhusbdx86_64` ?

**Comment by cheesebob04** [comment]
> Running code you don't understand can potentially change settings you wouldn't know how to restore, corrupt your machine, or even plain hacking it making it vulnerable.
Ah, yeah. Didn't think of that when troubleshooting, than
![IMG_3607](https://user-images.githubusercontent.com/75389012/218853893-1cf07adf-ddd5-4afe-a60e-2baeb046a47f.jpg)
ks for the info.

I did try doing `chmod +x vhusbdx86_64`, but it didn't seem to do anything (you can see me trying to run the command in the first screenshot in the issue post).

Here's the PC Controller shortcut.

**Comment by FlorianKempenich** [comment]
There's a typo in the **Launch Options**
You wrote `-fullscreen` when it should be `--fullscreen` (double `-`)
Try to fix it and re-open the issue if that doesn't work 👍
