### ISSUE TITLE
Can't exit (clicking/tapping inside circle doesn't exit)

### ISSUE THREAD

**Issue by depawlur** [FlorianKempenich/Deckpad#5]
Followed all the instruction but can't seem to be able to exit
(clicking/tapping inside circle doesn't exit)

it does bring up a keyboard when in Deck Mode, but when in  desktop mode it just doesn't do anything when I click/tap

**Comment by FlorianKempenich** [comment]
Unfortunately, this is a common issue, it works on my side and no matter what I try, I can't reproduce.
See #1 if there is anything that may help, or if you can add extra info that would help me isolate the issue
